model = "gpt-5-codex"
model_reasoning_effort = "high"
windows_wsl_setup_acknowledged = true

[mcp_servers.chrome-devtools]
command = "cmd"
args = ["/c","npx","-y","chrome-devtools-mcp@latest"]
startup_timeout_sec = 60.0
[mcp_servers.chrome-devtools.env]
APPDATA = 'C:\Users\Administrator\AppData\Roaming'
HOME = 'c:\Users\Administrator'
LOCALAPPDATA = 'c:\Users\Administrator\AppData\Local'
NODE_OPTIONS = "--dns-result-order=ipv4first"
SystemRoot = 'c:\Windows'

[mcp_servers.context7]
command = "cmd"
args = ["/c", "npx", "-y", "@upstash/context7-mcp", "--api-key", "${CONTEXT7_API_KEY}"]
startup_timeout_sec = 120.0
[mcp_servers.context7.env]
APPDATA = 'c:\Users\Administrator\AppData\Roaming'
HOME = 'c:\Users\Administrator'
LOCALAPPDATA = 'c:\Users\Administrator\AppData\Local'
NODE_OPTIONS = "--dns-result-order=ipv4first"
SystemRoot = 'c:\Windows'

[mcp_servers.filesystem]
command = "cmd"
args = ["/c", "npx", "-y", "@modelcontextprotocol/server-filesystem@latest"]
startup_timeout_sec = 60.0
[mcp_servers.filesystem.env]
APPDATA = 'c:\Users\Administrator\AppData\Roaming'
HOME = 'c:\Users\Administrator'
LOCALAPPDATA = 'c:\Users\Administrator\AppData\Local'
NODE_OPTIONS = "--dns-result-order=ipv4first"
SystemRoot = 'c:\Windows'

[mcp_servers.github]
command = "cmd"
args = ["/c", "npx", "-y", "@modelcontextprotocol/server-github@latest"]
startup_timeout_sec = 60.0
[mcp_servers.github.env]
APPDATA = 'c:\Users\Administrator\AppData\Roaming'
HOME = 'c:\Users\Administrator'
LOCALAPPDATA = 'c:\Users\Administrator\AppData\Local'
NODE_OPTIONS = "--dns-result-order=ipv4first"
SystemRoot = 'c:\Windows'

[mcp_servers.graphiti]
command = "cmd"
args = ["/c", "uv", "run", "--directory", "g:/workspace/graphiti/mcp_server", "graphiti_mcp_server.py", "--transport", "stdio"]
startup_timeout_sec = 60.0
[mcp_servers.graphiti.env]
APPDATA = 'c:\Users\Administrator\AppData\Roaming'
EMBEDDER_MODEL = "models/text-embedding-004"
GOOGLE_API_KEY = "AIzaSyC4YW25znj-zTc0BwEYmXf446XP8rNBFes"
HOME = 'c:\Users\Administrator'
LOCALAPPDATA = 'c:\Users\Administrator\AppData\Local'
MODEL_NAME = "gemini-2.5-pro"
NEO4J_PASSWORD = "graphiti123!"
NEO4J_URI = "bolt://127.0.0.1:7687"
NEO4J_USER = "neo4j"
NODE_OPTIONS = "--dns-result-order=ipv4first"
PYTHONIOENCODING = "utf-8"
PYTHONUNBUFFERED = "1"
SystemRoot = 'c:\Windows'

[mcp_servers.memory]
command = "cmd"
args = ["/c", "npx", "-y", "@modelcontextprotocol/server-memory@latest"]
startup_timeout_sec = 60.0
[mcp_servers.memory.env]
APPDATA = 'c:\Users\Administrator\AppData\Roaming'
HOME = 'c:\Users\Administrator'
LOCALAPPDATA = 'c:\Users\Administrator\AppData\Local'
NODE_OPTIONS = "--dns-result-order=ipv4first"
SystemRoot = 'c:\Windows'

[mcp_servers.playwright]
command = "cmd"
args = ["/c", "npx", "-y", "@playwright/mcp@latest"]
startup_timeout_sec = 180.0
[mcp_servers.playwright.env]
APPDATA = 'c:\Users\Administrator\AppData\Roaming'
HOME = 'c:\Users\Administrator'
LOCALAPPDATA = 'c:\Users\Administrator\AppData\Local'
NODE_OPTIONS = "--dns-result-order=ipv4first"
SystemRoot = 'c:\Windows'

[mcp_servers.puppeteer]
command = "cmd"
args = ["/c", "npx", "-y", "@modelcontextprotocol/server-puppeteer@latest"]
startup_timeout_sec = 90.0
[mcp_servers.puppeteer.env]
APPDATA = 'c:\Users\Administrator\AppData\Roaming'
HOME = 'c:\Users\Administrator'
LOCALAPPDATA = 'c:\Users\Administrator\AppData\Local'
NODE_OPTIONS = "--dns-result-order=ipv4first"
SystemRoot = 'c:\Windows'

[mcp_servers.sequential_thinking]
command = "cmd"
args = ["/c", "npx", "-y", "@modelcontextprotocol/server-sequential-thinking@latest"]
startup_timeout_sec = 60.0
[mcp_servers.sequential_thinking.env]
APPDATA = 'c:\Users\Administrator\AppData\Roaming'
HOME = 'c:\Users\Administrator'
LOCALAPPDATA = 'c:\Users\Administrator\AppData\Local'
NODE_OPTIONS = "--dns-result-order=ipv4first"
SystemRoot = 'c:\Windows'

[mcp_servers.stock]
command = "C:\\nvm4w\\nodejs\\npx.cmd"          # 或直接 "npx.cmd"
args = [
  "-y",
  "@gonzaloafidalgo/mcp-sse-bridge@latest",
  "http://82.156.17.205/cnstock/sse",          # ← 第一个位置参数
  "--allow-http",
  "--header", "API_KEY: ${API_KEY}"
]
startup_timeout_sec = 120.0                    # 留足缓冲

[mcp_servers.stock.env]
PATH         = "C:\\nvm4w\\nodejs;${PATH}"
API_KEY      = "value"
NODE_OPTIONS = "--dns-result-order=ipv4first"
HOME         = "C:\\Users\\Administrator"
LOCALAPPDATA = "C:\\Users\\Administrator\\AppData\\Local"
APPDATA      = "C:\\Users\\Administrator\\AppData\\Roaming"
SystemRoot   = "C:\\Windows"


[mcp_servers.supabase]
command = "cmd"
args = ["/c", "npx", "-y", "@supabase/mcp-server-supabase@latest", "--read-only", "--project-ref", "${SUPABASE_PROJECT_REF}"]
startup_timeout_sec = 120.0
[mcp_servers.supabase.env]
APPDATA = 'c:\Users\Administrator\AppData\Roaming'
HOME = 'c:\Users\Administrator'
LOCALAPPDATA = 'c:\Users\Administrator\AppData\Local'
NODE_OPTIONS = "--dns-result-order=ipv4first"
SUPABASE_ACCESS_TOKEN = "${SUPABASE_ACCESS_TOKEN}"
SystemRoot = 'c:\Windows'

[mcp_servers.taskmaster-ai]
command = "cmd"
args = ["/c", "npx", "-y", "--package=task-master-ai", "task-master-ai"]
startup_timeout_sec = 60.0
[mcp_servers.taskmaster-ai.env]
ANTHROPIC_API_KEY = "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"
APPDATA = 'c:\Users\Administrator\AppData\Roaming'
GOOGLE_API_KEY = "AIzaSyD3g5RMKIEIrDcmnEtPRNq_T_-vXBRsl5s"
HOME = 'c:\Users\Administrator'
LOCALAPPDATA = 'c:\Users\Administrator\AppData\Local'
NODE_OPTIONS = "--dns-result-order=ipv4first"
OLLAMA_API_KEY = "YOUR_OLLAMA_API_KEY_HERE"
OPENAI_API_KEY = "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"
OPENROUTER_API_KEY = "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"
SystemRoot = 'c:\Windows'
XAI_API_KEY = "xai-NV4cljzI3pwrL60WDedxpAVnbahutH3UEur1rEephauyWpuEqgHZdEElSZfcTCyIHpnqTQDg3qoDFm90"

[mcp_servers.zen]
command = "wsl"
args = ["/mnt/g/workspace/zen-mcp-server/.zen_venv/bin/python", "/mnt/g/workspace/zen-mcp-server/server.py"]
startup_timeout_sec = 90.0
[mcp_servers.zen.env]
APPDATA = 'c:\Users\Administrator\AppData\Roaming'
HOME = 'c:\Users\Administrator'
LOCALAPPDATA = 'c:\Users\Administrator\AppData\Local'
NODE_OPTIONS = "--dns-result-order=ipv4first"
SystemRoot = 'c:\Windows'



# ─── 工具开关 & 受信项目示例 ───────────────────────
[tools]
web_search = true

[projects.'g:/workspace/PTrade_trading']
trust_level = "trusted"

[projects.'C:\Users\Administrator']
trust_level = "trusted"
